### ISSUE TITLE
How many times we need to fit cuboid in about 1w points

### ISSUE THREAD

**Issue by zeal-up** [usamamehmood3/Cuboid-Fitting-RanSAC#1]
I am a Pythoner, not a matlab user. But I can not found else cuboid fitting package in python(actually I found one but not what I want). I reimplement your program in python but it cost me too many times in one fit. Thus I want to ask what the time cost in matlab. 
Appreciate if you can reply.

**Comment by usamamehmood3** [comment]
It takes 3.364790 seconds to fit the cuboid to the Box.mat file that is provided. Let me know how I can help you further. Thanks!

**Comment by liaoksn** [comment]
> I am a Pythoner, not a matlab user. But I can not found else cuboid fitting package in python(actually I found one but not what I want). I reimplement your program in python but it cost me too many times in one fit. Thus I want to ask what the time cost in matlab. Appreciate if you can reply.

hey,can you provide your python code ?
